---
- name: Installing dependencies
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - mysql-server-8.0
    - python3-mysqldb
    - php8.1-mysql

- name: Creating mysql db
  mysql_db:
    name: "{{ wp_db }}"
    login_user: root
    login_password: 123
    state: present
  notify:
    - Restarting mysql
    
- name: Creating mysqldb user
  mysql_user:
    name: "{{ wp_user }}"
    password: "{{ wp_user_pass }}"
    priv: "{{ wp_db }}.*:ALL"
    state: present
    host: "{{ item }}"
  loop:
    - "{{ wp_ip }}"

- name: Copying mysqld conf to the remote db host
  copy:
    src: files/my.cnf
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf